version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-pactum_db}
      POSTGRES_USER: ${POSTGRES_USER:-pactum_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pactum_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./inserts_postgres.sql:/docker-entrypoint-initdb.d/inserts_postgres.sql
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-pactum_user} -d ${POSTGRES_DB:-pactum_db}"]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py create_initial_superuser && python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:5000 Pactum.wsgi:application --log-level debug"
    volumes:
      - .:/app
    ports:
      - "5001:5000"
    environment:
      # ATENÇÃO: A SECRET_KEY está definida diretamente neste arquivo.
      # Para produção, é altamente recomendável usar uma variável de ambiente.
      - SECRET_KEY=35c449f8c8cdd048c40b53d0a6faef19ad61e0a3b599bfc198a8e63488a200d33765f59d32fdc4f93daef68597724526703c
      - DEBUG=${DEBUG:-False}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1,0.0.0.0}
      - DATABASE_URL=postgres://${POSTGRES_USER:-pactum_user}:${POSTGRES_PASSWORD:-pactum_password}@db:5432/${POSTGRES_DB:-pactum_db}
      - USE_POSTGRES=True
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: